In [2]:
import numpy as np
a1=np.arange(1,17).reshape(4,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
a2=np.arange(17,33).reshape(4,4)
a2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [4]:
a=np.concatenate((a1,a2))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [5]:
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [6]:
#HSTACK MEANS HORIZONTAL
np.hstack((a1,a2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [7]:
#VSTACK MEANS VERTICAL
np.vstack((a1,a2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
#SPLIT ARRAY
np.split(a1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [9]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
#HOW TO GENERATE RANDOM NUMBER
import random

In [13]:
#RANDOM VALUE GENERATE A RANDOM NUMBER BETWEEN 0 TO 1
np.random.random(2)

array([0.59026108, 0.27929544])

In [39]:
np.random.random(2)

array([0.39138605, 0.54463682])

In [47]:
np.random.random((3,3))

array([[0.31752262, 0.00165947, 0.70989121],
       [0.32493635, 0.57067093, 0.49688083],
       [0.72063117, 0.0752613 , 0.37019062]])

In [28]:
np.random.randint(1,4)

3

In [35]:
np.random.randint(1,4,(4,4))

array([[3, 1, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 2, 3],
       [2, 2, 2, 2]], dtype=int32)

In [51]:
#HOW TO ADD 2 STRING
s1=" India won match"
s2=" opposite to pok"
np.char.add(s1,s2)

np.str_(' India won match opposite to pok')

In [52]:
#UPPER CASE
np.char.upper(s2)

array(' OPPOSITE TO POK', dtype='<U16')

In [53]:
#LOWER CASE
np.char.lower(s1)

array(' india won match', dtype='<U16')

In [54]:
np.char.center(s1,50)

array('                  India won match                 ', dtype='<U50')