In [4]:
import numpy as np


In [5]:
a=np.array([1,2,3,4])
print(a)
type(a)
print(a.ndim)

[1 2 3 4]
1


In [8]:
a.dtype

dtype('int64')

In [6]:
#2d Array
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
a1.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [12]:
#3d Array
a1=np.array([[[1,2,3],[3,4,5],[6,7,8],[1,6,8]]])
print(a1)
a1.ndim

[[[1 2 3]
  [3 4 5]
  [6 7 8]
  [1 6 8]]]


3

In [13]:
#CHECK SIZE
a1.size

12

In [14]:
#CHECK SHAPE
a1.shape

(1, 4, 3)

In [15]:
#CHANGE THE DATA TYPE TO CONVERT TO A BOOLEAN,INT,ETC FROM
a=np.ones((5,3),dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
a=np.zeros((5,3),dtype=bool)
print(a)

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [17]:
a=np.ones((5,3),dtype=complex)
print(a)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [20]:
a=np.ones((5,3),dtype=float)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
a=np.ones((5,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
#TO CREATE EMPTY MATRIX

a=np.empty((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
#RANGE
#a=np.arange(start,end steps)
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
#ODD NUMBER
b=np.arange(1,13,2)
print(b)

[ 1  3  5  7  9 11]


In [28]:
#LINSPACE()
#TO FIND VALUES BETN 1 TO 9
np.linspace(1,9,3)

array([1., 5., 9.])

In [29]:
#TO FIND VALUES BETN 1 TO 6
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [30]:
#a=np.arange(start,end)

a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
#RESHAPE

b=a.reshape(4,3)
print(b)
b.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

In [9]:
array1d=np.array([1,2,3,4])
print(array1d)
array1d.ndim

[1 2 3 4]


1

In [10]:
ar_2d=array1d.reshape(2,2)
print(ar_2d)

[[1 2]
 [3 4]]


In [16]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
##revel this function can convert multidimentional array in 1d
a=np.array(a)
print(a)
a.ravel()

[1 2 3 4]


array([1, 2, 3, 4])

In [18]:
ar=np.arange(1,13).reshape(2,2,3)
print(ar)
ar.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [20]:
## RAVAL THIS FUN CAM CONVERT MULTIDIMENSIONAL ARRAY IN 1d

a=np.array(ar)
print(a)
a.ravel()
      

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
a1.max()

np.int64(9)

In [25]:
a1.min()

np.int64(1)

In [29]:
import numpy as np

In [31]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
#TO PERFORM MATRIX PRODUCT MULTIPLICATION LIKE 1ST ROW 1ST COLUMN
m1=arr1@arr2 
print(m1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [34]:
m1.max()

np.int64(150)

In [35]:
m1.min()

np.int64(30)

In [36]:
m1.argmax()

np.int64(8)

In [37]:
#HOW TO FIND MAX VALUE IN ROW AND COLUMN
#0 ROWS
#1 COLUMN

m1.max(axis=0)

array([102, 126, 150])

In [39]:

m1.min(axis=1)

array([ 30,  66, 102])

In [40]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#FIND SUM OF ALL VALUE IN MATRIX
np.sum(arr1)

np.int64(45)

In [43]:
#FIND A SUM BASED ON ROW AND COLUMN
#COLUMN
np.sum(arr1,axis=0)

array([12, 15, 18])

In [44]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [45]:
np.mean(arr1)

np.float64(5.0)